// <auto-generated />
using System;
using BackendSF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendSF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630203746_CheckListaCrud")]
    partial class CheckListaCrud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendSF.Entities.AktivnostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokacija")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlanPutovanjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProcijenjeniTrosak")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<TimeSpan?>("Vrijeme")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("Aktivnosti", (string)null);
                });

            modelBuilder.Entity("BackendSF.Entities.DestinacijaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("datetime2");

                    b.Property<string>("KratakOpis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("PlanPutovanjaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("Destinacije", (string)null);
                });

            modelBuilder.Entity("BackendSF.Entities.PlanPutovanjaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKreiranjaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KrajnjiDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("KratakOpis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("OpsteNapomene")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("PlaniraniBudzet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PocetniDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlanoviPutovanja", (string)null);
                });

            modelBuilder.Entity("BackendSF.Entities.StavkaCheckListeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("PlanPutovanjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Zavrseno")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("StavkeCheckListe", (string)null);
                });

            modelBuilder.Entity("BackendSF.Entities.TrosakEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlanPutovanjaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("Troskovi", (string)null);
                });

            modelBuilder.Entity("BackendSF.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendSF.Entities.AktivnostEntity", b =>
                {
                    b.HasOne("BackendSF.Entities.PlanPutovanjaEntity", "PlanPutovanja")
                        .WithMany("Aktivnosti")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("BackendSF.Entities.DestinacijaEntity", b =>
                {
                    b.HasOne("BackendSF.Entities.PlanPutovanjaEntity", "PlanPutovanja")
                        .WithMany("Destinacije")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("BackendSF.Entities.PlanPutovanjaEntity", b =>
                {
                    b.HasOne("BackendSF.Entities.UserEntity", "User")
                        .WithMany("PlanoviPutovanja")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendSF.Entities.StavkaCheckListeEntity", b =>
                {
                    b.HasOne("BackendSF.Entities.PlanPutovanjaEntity", "PlanPutovanja")
                        .WithMany("StavkeCheckListe")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("BackendSF.Entities.TrosakEntity", b =>
                {
                    b.HasOne("BackendSF.Entities.PlanPutovanjaEntity", "PlanPutovanja")
                        .WithMany("Troskovi")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("BackendSF.Entities.PlanPutovanjaEntity", b =>
                {
                    b.Navigation("Aktivnosti");

                    b.Navigation("Destinacije");

                    b.Navigation("StavkeCheckListe");

                    b.Navigation("Troskovi");
                });

            modelBuilder.Entity("BackendSF.Entities.UserEntity", b =>
                {
                    b.Navigation("PlanoviPutovanja");
                });
#pragma warning restore 612, 618
        }
    }
}
